### ISSUE TITLE
unknown field ‘iterate_shared’ specified in initializer   .iterate_shared = apfs_readdir,

### ISSUE THREAD

**Issue by Glimpse-006** [linux-apfs/apfsprogs#1]
evs: linux ubuntu 
when  change to linux-pafs-oot directory and use the make cmd I met this question
：unknown field ‘iterate_shared’ specified in initializer
  .iterate_shared = apfs_readdir,

**Comment by eafer** [comment]
On Wed, Dec 11, 2019 at 04:37:35AM -0800, Glimpse-006 wrote:
> evs: linux ubuntu 
> when  change to linux-pafs-oot directory and use the make cmd I met this question
> ：unknown field ‘iterate_shared’ specified in initializer
>   .iterate_shared = apfs_readdir,

Thanks for the report. What's your kernel version?

**Comment by Glimpse-006** [comment]
I'm using the virtual machine under window.

**Comment by eafer** [comment]
>  I'm using the virtual machine under window.

But what's the output of "uname -r" ?

**Comment by Glimpse-006** [comment]
I'm using the virtual machine under Win7. VMware Workstation  14.0.0 build-6661328.
 cat /proc/version
Linux version 4.4.0-21-generic (buildd@lgw01-21) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) ) #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016

**Comment by Glimpse-006** [comment]
> I'm using the virtual machine under window.
> But what's the output of "uname -r" ?
error operation:I want  press ctr+enter to get  a newline,but the wap submit my contents.

**Comment by Glimpse-006** [comment]
the detail  error info 
lb@ubuntu:~/linux-apfs-oot$ sudo make
make -C /lib/modules/4.4.0-21-generic/build M=/home/lb/linux-apfs-oot
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-21-generic'
  CC [M]  /home/lb/linux-apfs-oot/dir.o
/home/lb/linux-apfs-oot/dir.c:185:2: error: unknown field ‘iterate_shared’ specified in initializer
  .iterate_shared = apfs_readdir,
  ^
/home/lb/linux-apfs-oot/dir.c:185:20: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .iterate_shared = apfs_readdir,
                    ^
/home/lb/linux-apfs-oot/dir.c:185:20: note: (near initialization for ‘apfs_dir_operations.write’)
scripts/Makefile.build:258: recipe for target '/home/lb/linux-apfs-oot/dir.o' failed
make[2]: *** [/home/lb/linux-apfs-oot/dir.o] Error 1
Makefile:1396: recipe for target '_module_/home/lb/linux-apfs-oot' failed
make[1]: *** [_module_/home/lb/linux-apfs-oot] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-21-generic'
Makefile:13: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by eafer** [comment]
>  cat /proc/version
> Linux version 4.4.0-21-generic (buildd@lgw01-21) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) ) #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016

You are using Linux 4.4, and ->iterate_shared() was introduced in 4.7.
Currently supported versions are from 4.9 onwards, so if you want to use
the module you will have to upgrade. You can also try to fix this yourself,
or contribute money in exchange for the feature.

**Comment by Glimpse-006** [comment]
Thank your reply.  I 'll updata the kernal and retry
