### ISSUE TITLE
Compiling in the wrong order fails

### ISSUE THREAD

**Issue by Luflosi** [linux-apfs/apfsprogs#13]
In a clean checkout of the source code, if I first (or only) build `apfs-label` with `make -C apfs-label`, it fails because the libraries haven't been compiled yet. If I compile `apfsck` first, it works.
Looking at [mkapfs](https://github.com/linux-apfs/apfsprogs/blob/f31d7c2d69d212ce381399d2bb1e91410f592484/mkapfs/Makefile) and [apfsck](https://github.com/linux-apfs/apfsprogs/blob/f31d7c2d69d212ce381399d2bb1e91410f592484/apfsck/Makefile), one can see that the Makefiles contain some code to build libraries ("Building libraries...") but [apfs-label](https://github.com/linux-apfs/apfsprogs/blob/f31d7c2d69d212ce381399d2bb1e91410f592484/apfs-label/Makefile) and [apfs-snap](https://github.com/linux-apfs/apfsprogs/blob/f31d7c2d69d212ce381399d2bb1e91410f592484/apfs-snap/Makefile) contain no such code.

I suggest copying the the relevant code from `mkapfs` or `apfsck` to `apfs-label` and `apfs-snap`.

This is not really a problem for me, I just thought I'd let you know of a small inconsistency, which might confuse people trying to compile this manually for the first time.

Edit: Maybe the code only needs to be copied to `apfs-label` and not `apfs-snap`.

**Comment by eafer** [comment]
Thanks, the makefiles here are a mess.

**Comment by eafer** [comment]
I think it should be fixed now, thanks again! Like you said, apfs-snap doesn't need to change, because that tool is very simple and doesn't use any of the common code. The problem here was that I copied the apfs-snap Makefile into apfs-label.

**Comment by Luflosi** [comment]
Yep, that fixes it. Thanks for the quick fix!
