### ISSUE TITLE
mkapfs on specific partition

### ISSUE THREAD

**Issue by tucari** [linux-apfs/apfsprogs#2]
Hi Ernesto,

Is it possible with the current mkapfs tool to format an already existing partition as APFS?

Thanks..

**Comment by eafer** [comment]
Hi,

On Fri, Jan 31, 2020 at 01:32:46PM -0800, tucari wrote:
> Is it possible with the current mkapfs tool to format an already existing
> partition as APFS?

Not without losing your data.  Be careful with this tool in general, it's
only experimental and filesystems are very delicate.

**Comment by atagunov** [comment]
@tucari trying to reach you on reddit..
