### ISSUE TITLE
Copy Files

### ISSUE THREAD

**Issue by 404meemr** [linux-apfs/apfsprogs#3]
How can I copy files to an APFS image I create with this tool? Do I need some other tool or can I just use `cp`?

**Comment by eafer** [comment]
On Fri, May 29, 2020 at 03:51:20PM -0700, Shreyas Lad wrote:
> How can I copy files to an APFS image I create with this tool? Do I need some other tool or can I just use `cp`?

On Linux or on MacOS?

On Linux, you can't: write support for the module is not yet ready. On a
Mac, cp should work. Keep in mind that this tool is experimental, so there's
always a risk of corruption.

**Comment by 404meemr** [comment]
alright thanks
